[build]
  command = "git clone https://github.com/flutter/flutter.git -b stable --depth 1 _flutter && export PATH=\"$PWD/_flutter/bin:$PATH\" && flutter config --no-analytics && flutter pub get && flutter build web --release --base-href /"
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
